package app;
/*
 * Click nbfs:
 * Click nbfs:
 */

/**
 *
 * @author Hype GLK
 */

import javax.swing.*;
import javax.swing.table.*;

import actor.Produk;
import com.formdev.flatlaf.FlatDarkLaf;

import java.awt.*;
import java.awt.event.*;
import panelKananGUI.*;
import service.AntrianService;
import service.FileHandlerService;
import service.ManajemenFile;
import service.*;

import java.util.ArrayList; 
import java.util.List;    

public class MainFrame extends javax.swing.JFrame {

    CardLayout kanan;
    JButton prev;

    
    private FileHandlerService fileHandlerService;
    private AntrianService antrianService;
    private List<Produk> daftarProduk;

    
    private pendaftaranPanel panelPendaftaran;
    private pelayananPanel panelPelayanan;
    private tambahProdukPanel panelTambahProduk;


    public MainFrame() {
        initComponents();
        kanan = (CardLayout) kananPanel.getLayout();

        
        fileHandlerService = new ManajemenFile();
        antrianService = new ManajemenAntrian(fileHandlerService); 
        
        daftarProduk = fileHandlerService.bacaDataProduk(ManajemenFile.PRODUK_FILE);
        antrianService.loadAntrianFromFile(ManajemenFile.ANTRIAN_FILE);


        
        
        panelPendaftaran = new pendaftaranPanel(antrianService, daftarProduk, this); 
        panelPelayanan = new pelayananPanel(antrianService, this); 
        panelTambahProduk = new tambahProdukPanel(daftarProduk, fileHandlerService, this); 

        
        kananPanel.add(panelPendaftaran, "pendaftaran");
        kananPanel.add(panelPelayanan, "pelayanan");
        kananPanel.add(panelTambahProduk, "produk");
        
        
        setDaftar(); 

        
        daftarButton.addActionListener(e -> setDaftar());
        pelayananButton.addActionListener(e -> setPelayanan());
        tambahProdukButton.addActionListener(e -> setProduk());

        
        this.setLocationRelativeTo(null);
    }

    void setPelayanan() {
        if (prev != null) {
            prev.setBackground(new Color(0, 51, 51));
        }
        pelayananButton.setBackground(new Color(0, 17, 17));
        prev = pelayananButton;
        panelPelayanan.refreshTampilanAntrian(); 
        kanan.show(kananPanel, "pelayanan");
    }

    void setDaftar() {
        if (prev != null) {
            prev.setBackground(new Color(0, 51, 51));
        }
        daftarButton.setBackground(new Color(0, 17, 17));
        prev = daftarButton;
        panelPendaftaran.muatUlangProdukComboBox(); 
        kanan.show(kananPanel, "pendaftaran");
    }

    void setProduk() {
        if (prev != null) {
            prev.setBackground(new Color(0, 51, 51));
        }
        tambahProdukButton.setBackground(new Color(0, 17, 17));
        prev = tambahProdukButton;
        kanan.show(kananPanel, "produk");
    }

    
    public void produkDitambahkan() {
        
        if (panelPendaftaran != null) {
            panelPendaftaran.muatUlangProdukComboBox();
        }
    }

    public void antrianDiperbarui() {
        
        if (panelPelayanan != null) {
            panelPelayanan.refreshTampilanAntrian();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kiriPanel = new javax.swing.JPanel();
        daftarButton = new javax.swing.JButton();
        pelayananButton = new javax.swing.JButton();
        tambahProdukButton = new javax.swing.JButton();
        kananPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Warung Baratie Queue System");
        setMaximumSize(new java.awt.Dimension(825, 575));
        setMinimumSize(new java.awt.Dimension(825, 575));

        headerPanel.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); 
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Warung Baratie");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        kiriPanel.setBackground(new java.awt.Color(0, 51, 51));

        daftarButton.setBackground(new java.awt.Color(0, 51, 51));
        daftarButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); 
        daftarButton.setForeground(new java.awt.Color(255, 255, 255));
        daftarButton.setText("Pendaftaran");
        daftarButton.setBorderPainted(false);
        daftarButton.setOpaque(true);

        pelayananButton.setBackground(new java.awt.Color(0, 51, 51));
        pelayananButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); 
        pelayananButton.setForeground(new java.awt.Color(255, 255, 255));
        pelayananButton.setText("Pelayanan");
        pelayananButton.setBorderPainted(false);
        pelayananButton.setOpaque(true);

        tambahProdukButton.setBackground(new java.awt.Color(0, 51, 51));
        tambahProdukButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); 
        tambahProdukButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahProdukButton.setText("Tambah Produk");
        tambahProdukButton.setBorderPainted(false);
        tambahProdukButton.setOpaque(true);

        javax.swing.GroupLayout kiriPanelLayout = new javax.swing.GroupLayout(kiriPanel);
        kiriPanel.setLayout(kiriPanelLayout);
        kiriPanelLayout.setHorizontalGroup(
            kiriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kiriPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kiriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daftarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pelayananButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tambahProdukButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                .addContainerGap())
        );
        kiriPanelLayout.setVerticalGroup(
            kiriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kiriPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(daftarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pelayananButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tambahProdukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        kananPanel.setBackground(new java.awt.Color(102, 102, 102));
        kananPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kiriPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(kananPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(kiriPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(kananPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http:
         */
        FlatDarkLaf.setup();
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    
    private javax.swing.JButton daftarButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel kananPanel;
    private javax.swing.JPanel kiriPanel;
    private javax.swing.JButton pelayananButton;
    private javax.swing.JButton tambahProdukButton;
    
}